### ISSUE TITLE
Bare-bones pipes implementation

### ISSUE THREAD

**Issue by cwohlman** [usefulio/pipes#1]
The idea behind pipes is to have a compose-able action processing pipeline and routes. Starting with an api like iron router's, which consists of routes (in our case named, not urls) which have an action+hooks, but building on (and streamlining) that paradigm to produce a more flexible, reusable package.

The basic pipes implementation should implement this api:

``` javascript
// Creates a new pipe with three stages, before, action, and after
// all the before hooks should run, then all of the action hooks, then all of the after hooks
var myPipe = new Pipe(['before', 'action', 'after']);

// Attaches an action hook (which is just a function) to the default route.
myPipe.on('default', 'action', function (message) {
  console.log("This is the first action for the default route, message:", message);
  return message;
});

// Attaches an after hook to the default route
myPipe.on('default', 'after', function (message) {
  console.log('sent', message) // should log the message after it has been run through the default action.
});

// Runs all of the hooks for the default route, in order, passing as data to the first hook
// 'This is my message' and as data to each subsequent hook the return value of the previous
// hook.
myPipe.do('default', "This is my message");

```

**Comment by ianserlin** [comment]
Should a pipe really have more than one `action`?

Also see https://github.com/substack/stream-handbook for inspiration.

The goal is to have a standard paradigm for chaining a series (or branched series) of function input and outputs.

**Comment by cwohlman** [comment]
My initial implementation of the pipe paradigm (`mailer-core`) suffered from the lack of a clear way to specify which action should occur first, and also a clear way to add additional functionality to an existing route. I realized that it is much more powerful to be able to compose routes in more than one way:

`a -> b` I want a to do whatever b does
`a -> b, a -> c` I realize I also want a to do whatever c does
`a -> b, a(0) -> d` I realize I also want to do what d does, but first, before b.

In the messages package for example, I wanted 2 kinds of actions: `message processors` and `message senders`, because I clearly want to do all my processing first, before I send using any service. But I probably also want to be able to add processors which run only for a particular sender. Using the paradigm above you can easily accomplish that (the sender is a named pipe, and so we can add pre-processors to it).

**Comment by cwohlman** [comment]
An alternate proposal would be to require a name for every function, and then allow developers to extend named actions at will.
